// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9MXHuqPVKUx5xNG8Lo4E0UxwrLVkaJOo',
    appId: '1:1077651074048:web:ff106b429f82e8ea58bce5',
    messagingSenderId: '1077651074048',
    projectId: 'fir-deneme-40f97',
    authDomain: 'fir-deneme-40f97.firebaseapp.com',
    storageBucket: 'fir-deneme-40f97.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8rYBRNpKlC_8BdG5mND-3dRPdvVS7VMU',
    appId: '1:1077651074048:android:4a73d9e849280f1358bce5',
    messagingSenderId: '1077651074048',
    projectId: 'fir-deneme-40f97',
    storageBucket: 'fir-deneme-40f97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACZH9N5M5grxp7iCf0nTkMG6hhJk9BgBM',
    appId: '1:1077651074048:ios:bbaf42a35f83f3fe58bce5',
    messagingSenderId: '1077651074048',
    projectId: 'fir-deneme-40f97',
    storageBucket: 'fir-deneme-40f97.appspot.com',
    iosBundleId: 'com.example.firebasedeneme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACZH9N5M5grxp7iCf0nTkMG6hhJk9BgBM',
    appId: '1:1077651074048:ios:293e9d6a8fc5161158bce5',
    messagingSenderId: '1077651074048',
    projectId: 'fir-deneme-40f97',
    storageBucket: 'fir-deneme-40f97.appspot.com',
    iosBundleId: 'com.example.firebasedeneme.RunnerTests',
  );
}
