// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjYVz-2iu2RTldqbCDdXHETe7Z4KXSbss',
    appId: '1:740543041181:web:404894ce27a36927d34e74',
    messagingSenderId: '740543041181',
    projectId: 'flutterexample1-1088a',
    authDomain: 'flutterexample1-1088a.firebaseapp.com',
    storageBucket: 'flutterexample1-1088a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATNoaatb8Ci8up_O62EbeYnIaRy4O1jfY',
    appId: '1:740543041181:android:49910878b8cb84dbd34e74',
    messagingSenderId: '740543041181',
    projectId: 'flutterexample1-1088a',
    storageBucket: 'flutterexample1-1088a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMXb0vGwuz6PmrCi-2xnXdh62YtqV9c-c',
    appId: '1:740543041181:ios:dab79bd83e9b7325d34e74',
    messagingSenderId: '740543041181',
    projectId: 'flutterexample1-1088a',
    storageBucket: 'flutterexample1-1088a.appspot.com',
    iosBundleId: 'com.example.firebaseexample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMXb0vGwuz6PmrCi-2xnXdh62YtqV9c-c',
    appId: '1:740543041181:ios:2e5e3247be413367d34e74',
    messagingSenderId: '740543041181',
    projectId: 'flutterexample1-1088a',
    storageBucket: 'flutterexample1-1088a.appspot.com',
    iosBundleId: 'com.example.firebaseexample.RunnerTests',
  );
}
